import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';
import './normalize.scss';
import { NavPanel } from '@/components/nav-panel/nav-panel';
import { Providers } from '@/redux/provider';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'SEP',
  description: 'Generated by create next app',
  other: { 'view-transition': 'same-origin' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`flex justify-center h-screen ${roboto.className}`}>
        <Providers>
          <main className="flex gap-0 max-w-[1920px] w-full h-[fit-content]">
            <NavPanel />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
