import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Dashboard } from "@/components/dashboard/dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`flex justify-center h-screen ${inter.className}`}>
        <main className="flex gap-4 max-w-7xl w-full">
          <Dashboard />
          <div className="w-full p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
