import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import './normalize.css';
import { Dashboard } from '@/components/dashboard/dashboard';
import { Providers } from '@/redux/provider';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'SEP',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`flex justify-center h-screen ${roboto.className}`}>
        <Providers>
          <main className="flex gap-2 max-w-7xl w-full">
            <Dashboard />
            <section className="w-full h-[100%] overflow-auto p-4">
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
